  // printf((statbuf.st_mode & S_IRUSR) ? "r" : "_");
        // printf((statbuf.st_mode & S_IWUSR) ? "w" : "_");
        // printf((statbuf.st_mode & S_IXUSR) ? "x" : "_");
        // printf((statbuf.st_mode & S_IRGRP) ? "r" : "_");
        // printf((statbuf.st_mode & S_IWGRP) ? "w" : "_");
        // printf((statbuf.st_mode & S_IXGRP) ? "x" : "_");
        // printf((statbuf.st_mode & S_IROTH) ? "r" : "_");
        // printf((statbuf.st_mode & S_IWOTH) ? "w" : "_");
        // printf((statbuf.st_mode & S_IXOTH) ? "x" : "_");
